[project]
name = "gas-delegate"
authors = ["Your Name <your.email@example.com>"]
description = "A decentralized gas delegation and optimization framework for Stacks blockchain"
telemetry = false
requirements = []

[contracts.delegation-auth]
path = "contracts/delegation-auth.clar"
depends_on = []

[contracts.gas-tracker]
path = "contracts/gas-tracker.clar"
depends_on = []

[contracts.delegation-manager]
path = "contracts/delegation-manager.clar"
depends_on = ["delegation-auth", "gas-tracker"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
